// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Field struct {
	Name string `json:"name"`
}

type PercentGroup struct {
	Name    string  `json:"name"`
	Percent float64 `json:"percent"`
}
